### ISSUE TITLE
Assigment of variables in objective function.

### ISSUE THREAD

**Issue by salmagro** [MMehrez/MPC-and-MHE-implementation-in-MATLAB-using-Casadi#3]
For the simulation of **Sim_4_MPC_Robot_tracking_mul_shooting.m**. When constructing the [Objective function](https://github.com/MMehrez/MPC-and-MHE-implementation-in-MATLAB-using-Casadi/blob/aa2176ac1619c30d8d952f496210a8e3c9de2ca0/workshop_github/Codes_casadi_v3_4_5/MPC_code/Sim_4_MPC_Robot_tracking_mul_shooting.m#L45), why the last opt_variables (X) are not been considered?

For example, in the case of N = 3 with the following setup:
```
K>> X

X = 
[[X_0, X_3, X_6, X_9], 
 [X_1, X_4, X_7, X_10], 
 [X_2, X_5, X_8, X_11]]
K>> P

P = 
[P_0, P_1, P_2, P_3, P_4, P_5, P_6, P_7, P_8, P_9, P_10, P_11, P_12, P_13, P_14, P_15, P_16, P_17]
K>> U

U = 
[[U_0, U_2, U_4], 
 [U_1, U_3, U_5]]
```
The **first iteration** of the objective function is comparing the first set of opt_variables (X_0, X_1, X_2) with the second set of parameters (P_3, P_4, P_5), as could be seen here:
```
K>> obj
obj = 
@1=0.5, @2=0.05, (((((sq((X_0-P_3))+sq((X_1-P_4)))+((@1*(X_2-P_5))*(X_2-P_5)))+(((@1*(U_0-P_6))*(U_0-P_6))+((@2*(U_1-P_7))*(U_1-P_7))))
```
In the last iteration the last optimization variables (X_9, X_10, X_11), neither the first parameters (P_0, P_1, P_2) are used for generating the obj function:
```

K>> obj
@1=0.5, @2=0.05, (((((((sq((X_0-P_3))+sq((X_1-P_4)))+((@1*(X_2-P_5))*(X_2-P_5)))+(((@1*(U_0-P_6))*(U_0-P_6))+((@2*(U_1-P_7))*(U_1-P_7))))+
((sq((X_3-P_8))+sq((X_4-P_9)))+((@1*(X_5-P_10))*(X_5-P_10))))+(((@1*(U_2-P_11))*(U_2-P_11))+((@2*(U_3-P_12))*(U_3-P_12))))+
((sq((X_6-P_13))+sq((X_7-P_14)))+((@1*(X_8-P_15))*(X_8-P_15))))+(((@1*(U_4-P_16))*(U_4-P_16))+((@2*(U_5-P_17))*(U_5-P_17))))
```

Why is that?

**Comment by MMehrez** [comment]
Thank you for your comments, here is my response to your questions:

**For the simulation of Sim_4_MPC_Robot_tracking_mul_shooting.m. When constructing the Objective function, why the last opt_variables (X) are not been considered?**

Because we are not using a terminal cost here. In this lecture, I used the simplest MPC formulation possible where we only use a running costs (I called it l), whose sum give the objective function. If you additionally add to this objective a penalization for the deviation of the last state, this extra term is called the terminal cost. 

**The first iteration of the objective function is comparing the first set of opt_variables (X_0, X_1, X_2) with the second set of parameters (P_3, P_4, P_5), as could be seen here:
In the last iteration the last optimization variables (X_9, X_10, X_11), neither the first parameters (P_0, P_1, P_2) are used for generating the obj function:
Why is that?**

because in the vector

P = 
[P_0, P_1, P_2, P_3, P_4, P_5, P_6, P_7, P_8, P_9, P_10, P_11, P_12, P_13, P_14, P_15, P_16, P_17],

(P_0, P_1, P_2)

are used to feed the current state measurement to our optimizer. Therefore, at the beginning of every MPC iteration, we do 

args.p(1:3) = x0; % initial condition of the robot posture, 

which basically sets the values (P_0, P_1, P_2). 

However, the remaining variable in P, i.e.

[P_3, P_4, P_5, P_6, P_7, P_8, P_9, P_10, P_11, P_12, P_13, P_14, P_15, P_16, P_17]

are used to set the reference trajectory for our state vector. 

Again, since we are not applying a terminal constraint on X, you won't see (X_9, X_10, X_11) in the objective (obj)

All the best,
Mohamed

**Comment by salmagro** [comment]
Thank you very much for the declaration. I have successfully deployed the MPC controller in a real vehicle using your approach.
